// SEARCH WIDGET
export const SUBMIT_QUERY = "SUBMIT_QUERY";
export const SAVE_QUERY = "SAVE_QUERY";
// export const SEARCH_LOADING = "SEARCH_LOADING";

// SEARCH RESULT TYPES
// export const SEARCH_RESULT_OVERVIEW = "SEARCH_RESULT_OVERVIEW";
// export const GET_INDIVIDUAL_HOTEL = "GET_INDIVIDUAL_HOTEL";
// export const CLEAR_DATA = "CLEAR_DATA";

// OVERVIEW
export const GET_DEPT = "GET_DEPT";
export const CLEAR_DEPT = "CLEAR_DEPT";

// EMPLOYEE TYPES
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const CHECK_EMPLOYEE = "CHECK_EMPLOYEE";
export const GET_SOME_EMPLOYEE = "GET_SOME_EMPLOYEE";
export const FIRE_EMPLOYEE = "FIRE_EMPLOYEE";
export const CLEAR_EMPLOYEE = "CLEAR_EMPLOYEE";
